DROP SEQUENCE WEATHER_GLOBAL_SEQ;
CREATE SEQUENCE WEATHER_GLOBAL_SEQ START WITH 100000;

CREATE TABLE NEWTASK.COUNTRY
(
  id INTEGER PRIMARY KEY,
  PATHID VARCHAR2(150),
  NAME VARCHAR2(150) CONSTRAINT country_unique UNIQUE
);

CREATE TABLE NEWTASK.CITY
(
  id INTEGER PRIMARY KEY,
  name VARCHAR2(150),
  pathName VARCHAR2(150) CONSTRAINT city_unique UNIQUE,
  partOfTerritory VARCHAR2(150),
  country_id INTEGER,
  CONSTRAINT CITY_AND_COUNTRY_CONSTRAINT FOREIGN KEY (country_id) REFERENCES COUNTRY (ID)
);

CREATE TABLE PERSON
(
  ID INTEGER PRIMARY KEY NOT NULL,
  CREATED TIMESTAMP(6),
  DAYOFWEEKFORSEND INTEGER,
  LASTSENDED TIMESTAMP(6),
  MAIL VARCHAR2(75) CONSTRAINT person_unique UNIQUE,
  NAME VARCHAR2(100),
  PREFCITY_ID NUMBER(10),
  CONSTRAINT PERSON_AND_CITY_CONSTRAINT FOREIGN KEY (PREFCITY_ID) REFERENCES CITY (ID)
);

CREATE TABLE WEATHER
(
  id INTEGER PRIMARY KEY,
  CITYREF_ID INTEGER,
  CITYNAME VARCHAR2(100),
  HUMIDITY VARCHAR2(5),
  PRESSURE VARCHAR2(30),
  REGISTRATIONDATE DATE,
  REGISTRATIONTIME DATE,
  SAVINGTIME TIMESTAMP(6),
  TEMPCURRENT NUMBER(10) NOT NULL,
  TEMPWATER NUMBER(10) NOT NULL,
  WEATHERCOMMENT VARCHAR2(100),
  WIND VARCHAR2(50),
  CONSTRAINT weather_unique UNIQUE (REGISTRATIONDATE, REGISTRATIONTIME, CITYNAME),
  CONSTRAINT WEATHER_AND_CITY_CONSTRAINT FOREIGN KEY (CITYREF_ID) REFERENCES CITY (ID)
);

/*
-- ALTER TABLE WEATHER ADD CONSTRAINT WEATHER_AND_CITY_CONSTRAINT FOREIGN KEY (CITYREF_ID) REFERENCES CITY (ID);

-- ALTER TABLE CITY ADD PATHNAME VARCHAR2(150);


ALTER TABLE PERSON ADD LASTSENDED TIMESTAMP(6);
ALTER TABLE PERSON ADD dayOfWeekForSend INTEGER;
ALTER TABLE PERSON DROP COLUMN SENDEVERYDAYS;
alter TABLE PERSON DROP COLUMN AGE;

ALTER TABLE WEATHER ADD FOREIGN KEY (CITYID) REFERENCES CITY (ID);
ALTER TABLE WEATHER DROP  COLUMN CITYID;

ALTER TABLE WEATHER ADD CONSTRAINT WEATHER_AND_CITY_CONSTRAINT FOREIGN KEY (CITYREF) REFERENCES CITY (ID);
RENAME WEATHER TO WEATHER_OLD;
ALTER TABLE WEATHER_OLD RENAME CONSTRAINT weather_unique to weather_unique_old;
alter TABLE WEATHER_OLD RENAME CONSTRAINT WEATHER_AND_CITY_CONSTRAINT to WEATHER_AND_CITY_CONSTR_OLD;

ALTER TABLE WEATHER DROP CONSTRAINT WEATHER_AND_CITY_CONSTRAINT;
ALTER TABLE WEATHER drop COLUMN CITYREF;

-- REFERENCES CITY


-- CONSTRAINT city_unique UNIQUE (name, country,partOfTerritory)
-- ALTER TABLE CITY ADD FOREIGN KEY (country) REFERENCES NEWTASK.COUNTRY (id) ;

ALTER TABLE NEWTASK.CITY ADD
  FOREIGN KEY (country) REFERENCES NEWTASK.COUNTRY (id);

-- alter table WEATHER modify WIND varchar2(50);

alter table WEATHER drop constraint weather_unique ;
alter table WEATHER add constraint weather_unique UNIQUE (REGISTRATIONDATE, REGISTRATIONTIME, CITYNAME);

-- UNIQUE INDEX ??

-- DROP CONSTRAINT constraint_name;
*/